package oodj.assignment;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Receipt_Dialog extends javax.swing.JDialog {

    /**
     * Creates new form Receipt_Dialog
     */
    public Receipt_Dialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Paid_to_Content_Label_R = new javax.swing.JLabel();
        Description1_Content_Label_R = new javax.swing.JLabel();
        Receipt_Title_Label_R = new javax.swing.JLabel();
        Date_Label_R = new javax.swing.JLabel();
        Paid_to_Label_R = new javax.swing.JLabel();
        Received_from_Label_R = new javax.swing.JLabel();
        Description_Label_R = new javax.swing.JLabel();
        Amount_Label_R = new javax.swing.JLabel();
        Time_Label_R = new javax.swing.JLabel();
        Close_B_R = new javax.swing.JButton();
        Date_Content_Label_R = new javax.swing.JLabel();
        Time_Content_Label_R = new javax.swing.JLabel();
        Received_from_Content_Label_R = new javax.swing.JLabel();
        Amount_Content_Label_R = new javax.swing.JLabel();
        Description2_Content_Label_R = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Receipt_Title_Label_R.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Receipt_Title_Label_R.setText("Receipt");

        Date_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Date_Label_R.setText("Date:");

        Paid_to_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Paid_to_Label_R.setText("Paid to:");

        Received_from_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Received_from_Label_R.setText("Received from:");

        Description_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Description_Label_R.setText("Description:");

        Amount_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Amount_Label_R.setText("Amount:");

        Time_Label_R.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        Time_Label_R.setText("Time:");

        Close_B_R.setText("Close");
        Close_B_R.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Close_B_RActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Receipt_Title_Label_R)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Date_Label_R)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Received_from_Label_R)
                                    .addComponent(Time_Label_R)
                                    .addComponent(Amount_Label_R)
                                    .addComponent(Paid_to_Label_R)
                                    .addComponent(Description_Label_R))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Description1_Content_Label_R)
                                    .addComponent(Paid_to_Content_Label_R)
                                    .addComponent(Amount_Content_Label_R)
                                    .addComponent(Time_Content_Label_R)
                                    .addComponent(Received_from_Content_Label_R)
                                    .addComponent(Date_Content_Label_R)
                                    .addComponent(Description2_Content_Label_R))))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(Close_B_R)
                .addGap(0, 93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Receipt_Title_Label_R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Date_Label_R)
                    .addComponent(Date_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Time_Label_R)
                    .addComponent(Time_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Received_from_Label_R)
                    .addComponent(Received_from_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Amount_Label_R)
                    .addComponent(Amount_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Paid_to_Label_R)
                    .addComponent(Paid_to_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Description_Label_R)
                    .addComponent(Description1_Content_Label_R))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Description2_Content_Label_R)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(Close_B_R)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Close_B_RActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Close_B_RActionPerformed
        dispose();
    }//GEN-LAST:event_Close_B_RActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receipt_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receipt_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receipt_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receipt_Dialog.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Receipt_Dialog dialog = new Receipt_Dialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Amount_Content_Label_R;
    private javax.swing.JLabel Amount_Label_R;
    private javax.swing.JButton Close_B_R;
    public javax.swing.JLabel Date_Content_Label_R;
    private javax.swing.JLabel Date_Label_R;
    public javax.swing.JLabel Description1_Content_Label_R;
    public javax.swing.JLabel Description2_Content_Label_R;
    private javax.swing.JLabel Description_Label_R;
    public javax.swing.JLabel Paid_to_Content_Label_R;
    private javax.swing.JLabel Paid_to_Label_R;
    private javax.swing.JLabel Receipt_Title_Label_R;
    public javax.swing.JLabel Received_from_Content_Label_R;
    private javax.swing.JLabel Received_from_Label_R;
    public javax.swing.JLabel Time_Content_Label_R;
    private javax.swing.JLabel Time_Label_R;
    // End of variables declaration//GEN-END:variables
}
