 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oodj.assignment;

/**
 *
 * @author Zacha
 */
public class StudentApplications extends javax.swing.JFrame {
    public static StudentApplications instance;
    /**
     * Creates new form StudentApplications
     */
    public StudentApplications() {
        initComponents();
        instance = this;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        dobLabel = new javax.swing.JLabel();
        genderLabel = new javax.swing.JLabel();
        nationalityLabel = new javax.swing.JLabel();
        contactLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        courseNameLabel = new javax.swing.JLabel();
        courseLength = new javax.swing.JLabel();
        currentYearLabel = new javax.swing.JLabel();
        dateSubbedLabel = new javax.swing.JLabel();
        preferedAreaLabel = new javax.swing.JLabel();
        preferedRoomType = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        acceptButton = new javax.swing.JToggleButton();
        rejectButton = new javax.swing.JToggleButton();
        backToNavigation = new javax.swing.JButton();
        studentNamesField = new javax.swing.JTextField();
        lookupStudentApplication = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chosenRoomIDField = new javax.swing.JTextField();
        showRoomsButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 204, 51));

        jLabel1.setFont(new java.awt.Font("Franklin Gothic Heavy", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Student: ");

        dobLabel.setForeground(new java.awt.Color(0, 0, 0));
        dobLabel.setText("Date of birth: ");

        genderLabel.setForeground(new java.awt.Color(0, 0, 0));
        genderLabel.setText("Gender:");

        nationalityLabel.setForeground(new java.awt.Color(0, 0, 0));
        nationalityLabel.setText("Nationality:");

        contactLabel.setForeground(new java.awt.Color(0, 0, 0));
        contactLabel.setText("Contact number:");

        emailLabel.setForeground(new java.awt.Color(0, 0, 0));
        emailLabel.setText("Email:");

        courseNameLabel.setForeground(new java.awt.Color(0, 0, 0));
        courseNameLabel.setText("Course name:");

        courseLength.setForeground(new java.awt.Color(0, 0, 0));
        courseLength.setText("Course length:");

        currentYearLabel.setForeground(new java.awt.Color(0, 0, 0));
        currentYearLabel.setText("Current year: ");

        dateSubbedLabel.setForeground(new java.awt.Color(0, 0, 0));
        dateSubbedLabel.setText("Date submitted: ");

        preferedAreaLabel.setForeground(new java.awt.Color(0, 0, 0));
        preferedAreaLabel.setText("Prefered area: ");

        preferedRoomType.setForeground(new java.awt.Color(0, 0, 0));
        preferedRoomType.setText("Prefered room type: ");

        startDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        startDateLabel.setText("Desired contract start date:");

        endDateLabel.setForeground(new java.awt.Color(0, 0, 0));
        endDateLabel.setText("Desired contract end date:");

        acceptButton.setText("Accept application");
        acceptButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acceptButtonActionPerformed(evt);
            }
        });

        rejectButton.setText("Reject application");
        rejectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rejectButtonActionPerformed(evt);
            }
        });

        backToNavigation.setText("Back to navigation");
        backToNavigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backToNavigationActionPerformed(evt);
            }
        });

        lookupStudentApplication.setText("lookup");
        lookupStudentApplication.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lookupStudentApplicationActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Assign to(Enter room ID):");

        chosenRoomIDField.setToolTipText("");

        showRoomsButton.setText("Show Rooms");
        showRoomsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showRoomsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(4, 4, 4)
                        .addComponent(studentNamesField, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateSubbedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                        .addGap(151, 151, 151))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(currentYearLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseLength, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(courseNameLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nationalityLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(genderLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lookupStudentApplication, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(preferedAreaLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                                .addComponent(preferedRoomType, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(contactLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dobLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(endDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(startDateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(backToNavigation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(showRoomsButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(acceptButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rejectButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(3, 3, 3)
                        .addComponent(chosenRoomIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dateSubbedLabel)
                    .addComponent(studentNamesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lookupStudentApplication)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(dobLabel)
                .addGap(18, 18, 18)
                .addComponent(genderLabel)
                .addGap(18, 18, 18)
                .addComponent(nationalityLabel)
                .addGap(18, 18, 18)
                .addComponent(contactLabel)
                .addGap(18, 18, 18)
                .addComponent(emailLabel)
                .addGap(18, 18, 18)
                .addComponent(courseNameLabel)
                .addGap(18, 18, 18)
                .addComponent(courseLength)
                .addGap(18, 18, 18)
                .addComponent(currentYearLabel)
                .addGap(18, 18, 18)
                .addComponent(preferedAreaLabel)
                .addGap(19, 19, 19)
                .addComponent(preferedRoomType)
                .addGap(51, 51, 51)
                .addComponent(startDateLabel)
                .addGap(18, 18, 18)
                .addComponent(endDateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(chosenRoomIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backToNavigation)
                    .addComponent(acceptButton)
                    .addComponent(rejectButton)
                    .addComponent(showRoomsButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rejectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rejectButtonActionPerformed
        AdminStudentApplication functions = new AdminStudentApplication();
        functions.setName(studentNamesField.getText());
        functions.rejectApplication();
        dobLabel.setText("Date of birth: ");
        courseLength.setText("Course Length: ");
        genderLabel.setText("Gender: ");
        nationalityLabel.setText("Nationality: ");
        contactLabel.setText("Contact number: ");
        emailLabel.setText("Email: ");
        courseNameLabel.setText("Course name: ");
        currentYearLabel.setText("Current year: ");
        preferedAreaLabel.setText("Preferred area: ");
        startDateLabel.setText("Desired contract start date: ");
        endDateLabel.setText("Desired contract end date: ");
        preferedRoomType.setText("Prefered room type: ");
        dateSubbedLabel.setText("Date submitted: ");
    }//GEN-LAST:event_rejectButtonActionPerformed

    private void showRoomsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showRoomsButtonActionPerformed
        AdminStudentApplication functions = new AdminStudentApplication();
        functions.showRooms();
    }//GEN-LAST:event_showRoomsButtonActionPerformed

    private void acceptButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acceptButtonActionPerformed
        AdminStudentApplication functions = new AdminStudentApplication();
        functions.setName(studentNamesField.getText());
        functions.acceptApplication(chosenRoomIDField.getText());
        dobLabel.setText("Date of birth: ");
        courseLength.setText("Course Length: ");
        genderLabel.setText("Gender: ");
        nationalityLabel.setText("Nationality: ");
        contactLabel.setText("Contact number: ");
        emailLabel.setText("Email: ");
        courseNameLabel.setText("Course name: ");
        currentYearLabel.setText("Current year: ");
        preferedAreaLabel.setText("Preferred area: ");
        startDateLabel.setText("Desired contract start date: ");
        endDateLabel.setText("Desired contract end date: ");
        preferedRoomType.setText("Prefered room type: ");
        dateSubbedLabel.setText("Date submitted: ");
    }//GEN-LAST:event_acceptButtonActionPerformed

    private void lookupStudentApplicationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lookupStudentApplicationActionPerformed
            AdminStudentApplication functions = new AdminStudentApplication();
            functions.setName(studentNamesField.getText());
            functions.lookupApplication();

            // Get the retrieved details from the AdminStudentApplication class
            String gender = functions.getGender();
            String nationality = functions.getNationality();
            String contactNumber = functions.getContact();
            String email = functions.getEmail();
            String courseName = functions.getCourse();
            String currentYear = functions.getCurrentYear();
            String preferedArea = functions.getRoomLocation();
            String startDate = functions.getContractStartDate();
            String endDate = functions.getContractEndDate();
            String length = functions.getCourseLength();
            String type = functions.getRoomType();
            String submitted = functions.getDateSubmitted();
            String dateOfBirth = functions.getBirthDate();
            
            // Set the retrieved details to the respective labels
            dobLabel.setText("Date of birth: " + dateOfBirth);
            courseLength.setText("Course Length: " + length);
            genderLabel.setText("Gender: " + gender);
            nationalityLabel.setText("Nationality: " + nationality);
            contactLabel.setText("Contact number: " + contactNumber);
            emailLabel.setText("Email: " + email);
            courseNameLabel.setText("Course name: " + courseName);
            currentYearLabel.setText("Current year: " + currentYear);
            preferedAreaLabel.setText("Preferred area: " + preferedArea);
            startDateLabel.setText("Desired contract start date: " + startDate);
            endDateLabel.setText("Desired contract end date: " + endDate);
            preferedRoomType.setText("Prefered room type: " + type);
            dateSubbedLabel.setText("Date submitted: " + submitted);
    }//GEN-LAST:event_lookupStudentApplicationActionPerformed

    private void backToNavigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backToNavigationActionPerformed
        AdminStudentApplication adminClass = new AdminStudentApplication();
        String confirmationPrompt = "Are you sure you want to return to navigation?";
        boolean confirmation = adminClass.showConfirmationPopup(confirmationPrompt);
        if(confirmation){
            Navigation.instance.setVisible(true);
            instance.setVisible(false);
        }
        else{
            System.out.println("Staying on current page.");
        }
    }//GEN-LAST:event_backToNavigationActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentApplications.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new StudentApplications().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton acceptButton;
    private javax.swing.JButton backToNavigation;
    private javax.swing.JTextField chosenRoomIDField;
    private javax.swing.JLabel contactLabel;
    private javax.swing.JLabel courseLength;
    private javax.swing.JLabel courseNameLabel;
    private javax.swing.JLabel currentYearLabel;
    private javax.swing.JLabel dateSubbedLabel;
    private javax.swing.JLabel dobLabel;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel genderLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lookupStudentApplication;
    private javax.swing.JLabel nationalityLabel;
    private javax.swing.JLabel preferedAreaLabel;
    private javax.swing.JLabel preferedRoomType;
    private javax.swing.JToggleButton rejectButton;
    private javax.swing.JButton showRoomsButton;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JTextField studentNamesField;
    // End of variables declaration//GEN-END:variables
}
